# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: ubuntu:21.04
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-443}:443'
        env_file:
            - .env.example
            - .env
        volumes:
            - '.:/var/www/html'
        networks:
            - app
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:?}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:?}'
            MYSQL_USER: '${DB_USERNAME:?}'
            MYSQL_PASSWORD: '${DB_PASSWORD:?}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - 'app-mysql:/var/lib/mysql'
        networks:
            - app
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    app:
        driver: bridge
volumes:
    app-mysql:
        driver: local
