#!/usr/bin/env bash

#if [ ! -z "$WWWUSER" ]; then
#    usermod -u $WWWUSER sail
#fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec "$@"
else
    cp .env.example .env
    printenv | sort
    composer install -n && \
        /usr/bin/php artisan key:generate && \
        /usr/bin/php artisan optimize:clear && \
        /usr/bin/php artisan migrate:fresh
    npm install && npm run prod
    printenv | sort
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
