#!/usr/bin/env bash

#if [ ! -z "$WWWUSER" ]; then
#    usermod -u $WWWUSER sail
#fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec "$@"
else
    cp .env.example .env
    source .env
    composer install -n && \
        /usr/bin/php artisan config:cache && \
        /usr/bin/php artisan migrate:fresh --force
    npm install && npm run prod
    #/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    /usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=443
fi
